version: '3.9'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env-example
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - env-example
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
volumes:
  data: