FROM maven:3.9.6-eclipse-temurin-21-alpine as builder
WORKDIR /app
COPY src /app/src
COPY pom.xml /app
RUN mvn clean package -DskipTests=true

FROM maven:3.9.6-eclipse-temurin-21-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","0.0.1-SNAPSHOT.jar"]